export const DDL_STATEMENTS: string[] = [
  `CREATE SCHEMA IF NOT EXISTS "public";`,
  `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Role') THEN CREATE TYPE "Role" AS ENUM ('ADMIN', 'VENDEDOR'); END IF; END $$;`,
  `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Status') THEN CREATE TYPE "Status" AS ENUM ('ACTIVE', 'INACTIVE'); END IF; END $$;`,
  `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'LotType') THEN CREATE TYPE "LotType" AS ENUM ('BEEF', 'PORK'); END IF; END $$;`,
  `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'MovementType') THEN CREATE TYPE "MovementType" AS ENUM ('ENTRADA', 'VENTA', 'AJUSTE', 'DEVOLUCION', 'MERMA'); END IF; END $$;`,
  `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'PaymentMethod') THEN CREATE TYPE "PaymentMethod" AS ENUM ('EFECTIVO', 'TRANSFERENCIA', 'TARJETA', 'NEQUI', 'DAVIPLATA', 'OTROS'); END IF; END $$;`,
  `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SaleStatus') THEN CREATE TYPE "SaleStatus" AS ENUM ('CONFIRMED', 'CANCELLED'); END IF; END $$;`,
  `CREATE TABLE IF NOT EXISTS "users" (
    "id" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'VENDEDOR',
    "status" "Status" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE TABLE IF NOT EXISTS "categories" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" "Status" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "categories_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE TABLE IF NOT EXISTS "cut_catalogs" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "meat_type" "LotType" NOT NULL,
    "description" TEXT,
    "status" "Status" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "cut_catalogs_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE TABLE IF NOT EXISTS "animal_lots" (
    "id" TEXT NOT NULL,
    "lot_type" "LotType" NOT NULL,
    "consecutive_number" INTEGER NOT NULL,
    "lot_code" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "description" TEXT,
    "purchase_price" DECIMAL(12,2) NOT NULL,
    "created_by_user_id" TEXT NOT NULL,
    "status" "Status" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "animal_lots_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE TABLE IF NOT EXISTS "lot_cuts" (
    "id" TEXT NOT NULL,
    "lot_id" TEXT NOT NULL,
    "cut_catalog_id" TEXT NOT NULL,
    "initial_weight" DECIMAL(10,3) NOT NULL,
    "current_stock" DECIMAL(10,3) NOT NULL,
    "price_per_kg" DECIMAL(12,2) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "lot_cuts_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE TABLE IF NOT EXISTS "products" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category_id" TEXT NOT NULL,
    "description" TEXT,
    "unit_measure" TEXT NOT NULL DEFAULT 'kg',
    "current_stock" DECIMAL(10,3) NOT NULL DEFAULT 0.000,
    "sale_price" DECIMAL(12,2) NOT NULL,
    "status" "Status" NOT NULL DEFAULT 'ACTIVE',
    "created_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE TABLE IF NOT EXISTS "sales" (
    "id" TEXT NOT NULL,
    "sale_number" TEXT NOT NULL,
    "consecutive_number" INTEGER NOT NULL,
    "user_id" TEXT NOT NULL,
    "payment_method" "PaymentMethod" NOT NULL DEFAULT 'EFECTIVO',
    "total_amount" DECIMAL(12,2) NOT NULL,
    "idempotency_key" TEXT NOT NULL,
    "status" "SaleStatus" NOT NULL DEFAULT 'CONFIRMED',
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "sales_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE TABLE IF NOT EXISTS "sale_items" (
    "id" TEXT NOT NULL,
    "sale_id" TEXT NOT NULL,
    "lot_cut_id" TEXT,
    "product_id" TEXT,
    "item_name" TEXT NOT NULL,
    "lot_code" TEXT,
    "quantity" DECIMAL(10,3) NOT NULL,
    "unit_price" DECIMAL(12,2) NOT NULL,
    "subtotal" DECIMAL(12,2) NOT NULL,
    CONSTRAINT "sale_items_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE TABLE IF NOT EXISTS "inventory_movements" (
    "id" TEXT NOT NULL,
    "movement_type" "MovementType" NOT NULL,
    "lot_cut_id" TEXT,
    "product_id" TEXT,
    "quantity" DECIMAL(10,3) NOT NULL,
    "previous_stock" DECIMAL(10,3) NOT NULL,
    "new_stock" DECIMAL(10,3) NOT NULL,
    "reference_id" TEXT,
    "user_id" TEXT NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "inventory_movements_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE TABLE IF NOT EXISTS "audit_logs" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "entity" TEXT NOT NULL,
    "entity_id" TEXT NOT NULL,
    "details" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE TABLE IF NOT EXISTS "system_settings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "business_name" TEXT NOT NULL DEFAULT 'Carnicería',
    "theme_color" TEXT NOT NULL DEFAULT 'red',
    "address" TEXT,
    "phone" TEXT,
    "receipt_note" TEXT,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "system_settings_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "users_username_key" ON "users"("username");`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "categories_name_key" ON "categories"("name");`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "cut_catalogs_name_meat_type_key" ON "cut_catalogs"("name", "meat_type");`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "animal_lots_lot_code_key" ON "animal_lots"("lot_code");`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "sales_sale_number_key" ON "sales"("sale_number");`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "sales_idempotency_key_key" ON "sales"("idempotency_key");`
];